// packages/counter-react/src/App.js
import React, { useEffect, useState } from 'react';
import countStore from 'containerReact/countStore';

export default () => {
  const [countState, setCountState] = useState(countStore.initialState);

  useEffect(() => {
    const subscription = countStore.subscribe(setCountState);
    countStore.init();

    return () => {
      subscription.unsubscribe();
    };
  }, []);

  return (
    <p>{`React Counter: ${countState.count}`}</p>
  );
};

// packages/counter-vue/src/App.vue
<template>
  <div id="counter-vue">
    <p>Vue Counter: {{ counterState.count }}</p>
  </div>
</template>

<script>
import countStore from 'containerReact/countStore';

export default {
  name: 'counterVue',
  data() {
    return {
      counterState: countStore.initialState
    }
  },
  methods: {
    setCounterState(newValue) {
      this.counterState = newValue;
    }
  },
  mounted() {
    countStore.subscribe(this.setCounterState);
  }
}
</script>
